#!/bin/bash

# loop through all the files in the folder

for answer_file in *.mdx; do
  existing_date=$(grep '^date:' "${answer_file}")
  if [[ -n "${existing_date}" ]]
  then
    echo "${answer_file} already has a date, skipping."
    continue
  fi

  date=$(git log -1 --pretty="format:%cI" "${answer_file}")
  touch "${answer_file}-new"
  new_file="${answer_file}-new"

  tr '\n' '^' < "${answer_file}" | sed "s/---/date:\n  ${date}\n---/2" | tr '^' '\n' > "${new_file}"

  mv "${new_file}" "${answer_file}"
done

