module.exports = {
  header: function({ cspAPI, sentryKey }) {
    return `
    Content-Security-Policy-Report-Only: upgrade-insecure-requests;
    default-src
      'none'
    ;
    script-src
      'self'
      'unsafe-inline'
      'unsafe-eval'
      www.sentry.dev
      www.googletagmanager.com
      www.google-analytics.com
      www.googleadservices.com
      js.driftt.com
      connect.facebook.net
      assets.calendly.com
      player.vimeo.com
      www.redditstatic.com
      m.servedby-buysellads.com
      static.zdassets.com
      googleads.g.doubleclick.net
      bat.bing.com
      munchkin.marketo.net
      cdn.bizible.com
      cdn.amplitude.com
      ${process.env.NEXT_PUBLIC_VERCEL_URL}
    ;
    connect-src
      'self'
      sentry.io
      *.sentry.io
      www.sentry.dev
      reload.getsentry.net
      api.amplitude.com
      api2.amplitude.com
      ekr.zdassets.com
      sentry.zendesk.com
      www.google-analytics.com
      stats.g.doubleclick.net
      776-mjn-501.mktoresp.com
      ${process.env.NEXT_PUBLIC_VERCEL_URL}
    ;
    img-src
      'self'
      data:
      www.sentry.dev
      sentry-blog.storage.googleapis.com
      images.ctfassets.net
      www.google-analytics.com
      stats.g.doubleclick.net
      assets.calendly.com
      q.quora.com
      alb.reddit.com
      www.facebook.com
      www.googletagmanager.com
      bat.bing.com
      www.google.com
      i.vimeocdn.com
      i.ytimg.com
      cdn.bizible.com
      cdn.bizibly.com
      ${process.env.NEXT_PUBLIC_VERCEL_URL}
    ;
    style-src
      'self'
      'unsafe-inline'
      www.sentry.dev
      assets.calendly.com
      fonts.googleapis.com
      ${process.env.NEXT_PUBLIC_VERCEL_URL}
    ;
    media-src
      'self'
      videos.ctfassets.net
      ${process.env.NEXT_PUBLIC_VERCEL_URL}
    ;
    font-src
      'self'
      www.sentry.dev
      fonts.gstatic.com
      ${process.env.NEXT_PUBLIC_VERCEL_URL}
    ;
    frame-src
      player.vimeo.com
      www.youtube-nocookie.com
      js.driftt.com
      calendly.com
      bid.g.doubleclick.net
      ${process.env.NEXT_PUBLIC_VERCEL_URL}
    ;
    manifest-src
      'self'
      www.sentry.dev
      ${process.env.NEXT_PUBLIC_VERCEL_URL}
    ;
    report-uri https://o1.ingest.sentry.io/api/${cspAPI}/security/?sentry_key=${sentryKey}
  `
      .replace(/\s+/gi, ' ')
      .replace(/\s;/gi, ';')
      .trim();
  },
};
